blank_issues_enabled: false

contact_links:
  - name: ğŸ› Comunique um problema
    url: https://github.com/zoonk/manual/discussions/new?category=problemas
    about: Comunique um problema que precisa ser corrigido.
    
  - name: ğŸ’¡ FaÃ§a uma sugestÃ£o
    url: https://github.com/zoonk/manual/discussions/new?category=ideias
    about: Compartilhe ideias para melhorar o nosso trabalho.
    
  - name: ğŸ™ PeÃ§a ajuda
    url: https://github.com/zoonk/manual/discussions/new?category=ajuda
    about: Tire qualquer dÃºvida que vocÃª tenha.
  
